<?php

if ( !defined( 'ABSPATH' ) ) {
    exit;
}
// Add the menu item to the admin menu for settings
add_action( 'admin_menu', 'ai_tts_add_admin_menu' );
function ai_tts_add_admin_menu() {
    add_options_page(
        esc_html__( 'AI Text-to-Speech', 'ai-text-to-speech' ),
        esc_html__( 'AI Text-to-Speech', 'ai-text-to-speech' ),
        'manage_options',
        'ai-text-to-speech',
        'ai_tts_options_page'
    );
}

// Get Specific Option
function ai_tts_get_option(  $option  ) {
    $options = get_option( 'ai_tts_settings' );
    if ( isset( $options[$option] ) && $options[$option] != '' ) {
        return sanitize_text_field( $options[$option] );
    }
    $default_options = [
        'file_storage_location'      => 'local',
        'dropbox_app_key'            => '',
        'dropbox_app_secret'         => '',
        'dropbox_access_token'       => '',
        'dropbox_token_expires'      => '',
        'show_player_label'          => true,
        'player_label'               => 'Listen to the audio version of this article (generated by AI).',
        'post_types'                 => 'all',
        'post_types_to_enable'       => array(),
        'include_title'              => true,
        'include_author'             => true,
        'include_date'               => true,
        'custom_text_before_content' => '',
        'custom_text_after_content'  => '',
        'player_background_color'    => '#f1f1f1',
        'player_height'              => 'default',
        'player_speed'               => '1',
        'enable_statistics'          => true,
        'last_usage_check'           => '',
        'error_log'                  => '',
    ];
    $default_options = array_map( 'sanitize_text_field', $default_options );
    return $default_options[$option];
}

// Update specific option
function ai_tts_update_option(  $option, $value  ) {
    $options = get_option( 'ai_tts_settings' );
    if ( !$options ) {
        $options = array();
    }
    $options[$option] = $value;
    update_option( 'ai_tts_settings', $options );
}

// Options page callback
function ai_tts_options_page() {
    ?>
    <div class="wrap ai-tts-settings">

        <h1><?php 
    echo esc_html__( 'AI Text-to-Speech', 'ai-text-to-speech' );
    ?>

        <?php 
    if ( ai_tts_get_option( 'enable_statistics' ) || !aitts_fs()->is_paying_or_trial() ) {
        ?>
        <span style="<?php 
        if ( !aitts_fs()->is_paying_or_trial() ) {
            // Free only
            ?>cursor: not-allowed;<?php 
        }
        ?>">
        <a href="<?php 
        echo admin_url( 'admin.php?page=ai-text-to-speech-stats' );
        ?>" class="button button-primary"
        style="margin-left: 10px;<?php 
        if ( !aitts_fs()->is_paying_or_trial() ) {
            // Free only
            ?>pointer-events: none;<?php 
        }
        ?>">
            <?php 
        echo esc_html__( 'View Statistics', 'ai-text-to-speech' );
        ?>
            <?php 
        if ( !aitts_fs()->is_paying_or_trial() ) {
            // Free only
            ?>
                <span>(PRO)</span>
            <?php 
        }
        ?>
            <span class="dashicons dashicons-chart-bar" style="text-decoration: none; font-size: 19px; margin-top: 5px;"></span>
        </a>
        </span>
        <?php 
    }
    ?>

        <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Free only
        ?>
            <a href="<?php 
        echo admin_url( 'admin.php?page=ai-text-to-speech-pricing' );
        ?>"
            class="button button-secondary" style="margin-left: 10px; background-color: green; color: #fff; border: none;">
                <?php 
        echo esc_html__( 'Upgrade to PRO', 'ai-text-to-speech' );
        ?> <span class="dashicons dashicons-star-filled" style="text-decoration: none; font-size: 19px; margin-top: 5px;"></span>
            </a>                
        <?php 
    }
    ?>
        </h1>
        <p><?php 
    echo esc_html__( 'Generate a TTS audio file for any post on your website, which is automatically displayed in an audio player at the top of the post content.', 'ai-text-to-speech' );
    ?></p>
        <hr style="margin: 25px 0 25px 0;" />
        <!-- Key input -->
        <form method="post" action="options.php">
            <?php 
    settings_fields( 'ai_tts_settings' );
    ?>
            <?php 
    do_settings_sections( 'ai_tts_settings' );
    ?>

            <h2><?php 
    echo esc_html__( 'API Settings', 'ai-text-to-speech' );
    ?></h2>

            <table class="form-table">
                <!-- OpenAI API Key (Not saved in the single option) -->
                <tr valign="top">
                    <th scope="row"><?php 
    echo esc_html__( 'OpenAI API Secret Key', 'ai-text-to-speech' );
    ?></th>
                    <td>
                        <?php 
    $api_key = get_option( 'ai_tts_api_key' );
    $disabled = '';
    $placeholder = '';
    $title = '';
    if ( defined( 'AI_TTS_API_KEY' ) ) {
        $api_key = AI_TTS_API_KEY;
        $api_key = substr( $api_key, 0, strlen( $api_key ) / 2 ) . str_repeat( '*', strlen( $api_key ) / 2 );
        $disabled = 'disabled';
        $placeholder = 'placeholder="' . esc_html__( '*Set in wp-config.php*', 'ai-text-to-speech' ) . '"';
        $title = 'title="' . esc_html__( 'This option is set in wp-config.php', 'ai-text-to-speech' ) . '"';
    }
    ?>
                        <input type="text" name="ai_tts_api_key" value="<?php 
    echo esc_attr( $api_key );
    ?>" <?php 
    echo esc_html( $disabled );
    ?> <?php 
    echo esc_html( $placeholder );
    ?> <?php 
    echo esc_html( $title );
    ?> />
                        <!-- API Help Button -->
                        <p>
                            <a class="api-help-button" href="#"><?php 
    echo esc_html__( 'How to get started', 'ai-text-to-speech' );
    ?><span class="dashicons dashicons-arrow-down-alt2" style="text-decoration: none; font-size: 14px; margin-top: 5px;"></span></a>
                        </p>
                        <p class="api-help" style="display: none; padding: 10px; background-color: #fff; border-radius: 5px;">
                            - <?php 
    echo sprintf( wp_kses_post( __( 'To get started, you will need to <a href="%s" target="_blank">create an account with OpenAI</a>, then setup your <a href="https://platform.openai.com/settings/organization/billing/overview" target="_blank">billing and credit balance</a>.', 'ai-text-to-speech' ) ), 'https://platform.openai.com/signup' );
    ?>
                            <br/>- <?php 
    echo esc_html__( 'Once you have created an account, you can generate an API secret key here:', 'ai-text-to-speech' );
    ?> <a href="https://platform.openai.com/api-keys" target="_blank"><?php 
    echo esc_html__( 'Generate API Key', 'ai-text-to-speech' );
    ?></a> 
                            <br/>- <?php 
    echo esc_html__( 'Copy and paste the API key into the field above, and click Save Changes.', 'ai-text-to-speech' );
    ?>
                            <br/>- <?php 
    echo esc_html__( 'You can then generate TTS audio files for your posts, in the "AI Text to Speech" section of the post editor sidebar.', 'ai-text-to-speech' );
    ?>
                        </p>
                    </td>
                </tr>
                <!-- On Click API Help Button, show the API Help -->
                <script>
                jQuery(document).ready(function($) {
                    $('.api-help-button').click(function() {
                        if($('.api-help').is(':visible')) {
                            $('.api-help').css('display', 'none');
                        } else {
                            $('.api-help').css('display', 'inline-block');R
                        }
                    });
                });
                </script>
                <!-- Pricing information -->
                <tr>
                    <th scope="row"><?php 
    echo esc_html__( 'OpenAI TTS Pricing', 'ai-text-to-speech' );
    ?></th>
                    <td>
                        <p><?php 
    echo esc_html__( 'OpenAI charges $0.015 per 1000 characters converted from text to spoken audio.', 'ai-text-to-speech' );
    ?> <a href="https://openai.com/pricing" target="_blank"><?php 
    echo esc_html__( 'Read more about the pricing here.', 'ai-text-to-speech' );
    ?></a></p>
                        <p>- <?php 
    echo esc_html__( 'It is your responsibility to keep track of your usage and cost in your', 'ai-text-to-speech' );
    ?> <a href="https://platform.openai.com/" target="_blank"><?php 
    echo esc_html__( 'OpenAI account', 'ai-text-to-speech' );
    ?></a>. <?php 
    echo sprintf( wp_kses_post( __( 'Be sure to <a href="%s" target="_blank">set your own monthly usage limits</a>.', 'ai-text-to-speech' ) ), 'https://platform.openai.com/account/limits' );
    ?></p>
                        <p>- <?php 
    echo sprintf( wp_kses_post( __( 'Keep your account <a href="%s" target="_blank">credit balance</a> topped up or the TTS generation may fail.', 'ai-text-to-speech' ) ), 'https://platform.openai.com/settings/organization/billing/overview' );
    ?></p>
                        <p>- <?php 
    echo esc_html__( 'The OpenAI charges and estimate costs shown in this plugin are for convenience only and may not be 100% accurate.', 'ai-text-to-speech' );
    ?></p>
                    </td>
                </tr>
                <!-- Show current OpenAI monthly spend -->
                <tr valign="top">
                    <th scope="row"><?php 
    echo esc_html__( 'OpenAI Usage Today', 'ai-text-to-speech' );
    ?></th>
                    <td>
                        <?php 
    $api_key = get_option( 'ai_tts_api_key' );
    $check_api = true;
    // Only check every 5 minutes
    if ( ai_tts_get_option( 'last_usage_check' ) ) {
        $last_usage_check = strtotime( ai_tts_get_option( 'last_usage_check' ) );
        $time_diff = time() - $last_usage_check;
        if ( $time_diff < 300 ) {
            $check_api = false;
        }
    }
    if ( $check_api ) {
        if ( $api_key ) {
            $date = gmdate( 'Y-m-d' );
            if ( !$date ) {
                $date = date( 'Y-m-d' );
            }
            $url = 'https://api.openai.com/v1/usage?date=' . $date;
            $args = array(
                'headers' => array(
                    'Authorization' => 'Bearer ' . $api_key,
                ),
            );
            $response = wp_remote_get( $url, $args );
            // Check for WP_Error or non-200 status code.
            if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
                echo '<p style="color: red; font-weight: bold;">';
                echo esc_html__( 'Error fetching data. There may be an issue with your Open API key or connection to api.openai.com', 'ai-text-to-speech' );
                echo '</p>';
                if ( is_wp_error( $response ) ) {
                    echo '<p>';
                    echo 'Error message: ' . esc_html( $response->get_error_message() );
                    ai_tts_add_to_error_log( 'Error fetching usage data: ' . $response->get_error_message() );
                    echo '</p>';
                }
                if ( 200 !== wp_remote_retrieve_response_code( $response ) && wp_remote_retrieve_response_code( $response ) ) {
                    echo '<p>';
                    echo 'Response code: ' . esc_html( wp_remote_retrieve_response_code( $response ) ) . " " . esc_html( wp_remote_retrieve_response_message( $response ) );
                    ai_tts_add_to_error_log( 'Error fetching usage data: ' . wp_remote_retrieve_response_code( $response ) . " " . wp_remote_retrieve_response_message( $response ) );
                    echo '</p>';
                }
            } else {
                $body = json_decode( wp_remote_retrieve_body( $response ) );
                // Process the response body.
                $total_characters_used = 0;
                $total_requests = 0;
                if ( isset( $body->tts_api_data ) && is_array( $body->tts_api_data ) ) {
                    foreach ( $body->tts_api_data as $item ) {
                        // Ensure that the required properties exist.
                        if ( isset( $item->num_characters ) && isset( $item->num_requests ) ) {
                            $total_characters_used += $item->num_characters;
                            $total_requests += $item->num_requests;
                        }
                    }
                }
                // Output the results.
                echo esc_html__( 'Total Characters Used:', 'ai-text-to-speech' ) . " " . esc_html( $total_characters_used ) . "<br>";
                echo "<span title='1 request is made for roughly every 1-2 sentences generated.'>" . esc_html__( 'Total Requests:', 'ai-text-to-speech' ) . " " . esc_html( $total_requests ) . "</span>";
                $total_cost = $total_characters_used / 1000 * 0.015;
                $total_cost = round( $total_cost, 4 );
                echo "<br>" . esc_html__( 'Total Cost:', 'ai-text-to-speech' ) . " \$" . esc_html( $total_cost );
            }
        } else {
            echo esc_html__( 'No API key set.', 'ai-text-to-speech' );
        }
    }
    ?>
                    </td>
                </tr>
                <?php 
    $ai_tts_error_log = ai_tts_get_option( 'error_log' );
    if ( $ai_tts_error_log ) {
        ?>
                <tr>
                    <th scope="row"></th>
                    <td>
                        <?php 
        echo '<p style="color: red; font-weight: bold;">';
        echo esc_html__( 'Error Log:', 'ai-text-to-speech' );
        echo ' <a href="?page=ai-text-to-speech&clear_error_log=1" style="text-decoration: underline;">' . esc_html__( 'Delete', 'ai-text-to-speech' ) . '</a>';
        echo '</p>';
        echo '<span style="max-height: 50px; overflow: auto; display: block; border: 1px solid #ccc; padding: 10px; background-color: #f1f1f1;">';
        $ai_tts_error_log = str_replace( "/n", "<br>", $ai_tts_error_log );
        $ai_tts_error_log = substr( $ai_tts_error_log, 4 );
        echo wp_kses_post( $ai_tts_error_log );
        echo '</span>';
        ?>
                    </td>
                </tr>
                <?php 
    }
    ?>
                </table>

                <?php 
    if ( isset( $_GET['clear_error_log'] ) && $_GET['clear_error_log'] == 1 ) {
        $options = get_option( 'ai_tts_settings' );
        if ( !$options ) {
            $options = array();
        }
        $options['error_log'] = '';
        update_option( 'ai_tts_settings', $options );
        wp_redirect( admin_url( 'options-general.php?page=ai-text-to-speech' ) );
        exit;
    }
    ?>

                <hr style="margin: 21px 0 29px 0;" />

                <h2><?php 
    echo esc_html__( 'File Storage', 'ai-text-to-speech' );
    ?></h2>

                <table class="form-table">
                    <!-- Select file storage location -->
                    <tr valign="top">
                        <th scope="row"><?php 
    echo esc_html__( 'File Storage Location', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <?php 
    if ( !aitts_fs()->is_paying_or_trial() && ai_tts_get_option( 'file_storage_location' ) != 'local' ) {
        ai_tts_update_option( 'file_storage_location', 'local' );
    }
    ?>                                
                            <select name="ai_tts_settings[file_storage_location]">
                                <option value="local" <?php 
    selected( ai_tts_get_option( 'file_storage_location' ), 'local' );
    ?>><?php 
    echo esc_html__( 'Local', 'ai-text-to-speech' );
    ?></option>
                                <option value="dropbox" <?php 
    selected( ai_tts_get_option( 'file_storage_location' ), 'dropbox' );
    ?>
                                    <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>disabled<?php 
    }
    ?>>
                                    <?php 
    echo esc_html__( 'Dropbox (PRO)', 'ai-text-to-speech' );
    ?>
                                </option>
                            </select>
                        </td>
                    </tr>
                </table>

                <table class="form-table ai-tts-local-credentials" style="margin-top: 0;">
                    <tr valign="top">
                        <th scope="row"><?php 
    echo esc_html__( 'Local Storage', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <p><?php 
    echo esc_html__( 'TTS audio files are stored in the uploads directory at', 'ai-text-to-speech' );
    ?> <code>/wp-content/uploads/ai-text-to-speech/</code></p>
                        </td>
                    </tr>
                </table>

                <table class="form-table ai-tts-dropbox-credentials" style="margin-top: 0; display: none;">
                    <?php 
    if ( empty( get_option( 'ai_tts_dropbox_refresh_token' ) ) ) {
        ?>
                    <!-- If Dropbox is selected, show the Dropbox API credentials -->
                    <tr valign="top">
                        <th scope="row"></th>
                        <td style="padding-top: 0;">
                            <p><?php 
        echo sprintf( wp_kses_post( __( 'To get started, you will need to <a href="%s" target="_blank">create an app with Dropbox</a>.', 'ai-text-to-speech' ) ), 'https://www.dropbox.com/developers/apps/create' );
        ?></p>
                            <p>1) <?php 
        echo esc_html__( 'Ensure you have set the app permissions to have: files.content.write, files.content.read, files.metadata.write, files.metadata.read, sharing.write', 'ai-text-to-speech' );
        ?></p>
                            <p>2) <?php 
        echo esc_html__( 'Add the following URL to the Redirect URIs in your app settings:', 'ai-text-to-speech' );
        ?> <code><?php 
        echo esc_url( admin_url( 'admin-post.php?action=aitts_dropbox_callback' ) );
        ?></code></p>
                            <p>3) <?php 
        echo esc_html__( 'Once you have created an app, you can get your key and secret here:', 'ai-text-to-speech' );
        ?> <a href="https://www.dropbox.com/developers/apps" target="_blank"><?php 
        echo esc_html__( 'App Settings', 'ai-text-to-speech' );
        ?></a></p>
                            <p>4) <?php 
        echo esc_html__( 'Copy and paste the App Key and App Secret into the fields below.', 'ai-text-to-speech' );
        ?></p>
                            <p>5) <?php 
        echo esc_html__( 'Click the "Connect to Dropbox" button to authenticate your app.', 'ai-text-to-speech' );
        ?></p>
                        </td>
                    </tr>
                    <?php 
    } else {
        ?>
                    <tr valign="top">
                        <th scope="row"><?php 
        echo esc_html__( 'Dropbox Storage', 'ai-text-to-speech' );
        ?></th>
                        <td>
                            <p><?php 
        echo esc_html__( 'TTS audio files are stored in your Dropbox account at:', 'ai-text-to-speech' );
        ?> <code>/Apps/AppName/DomainName/</code></p>
                        </td>
                    </tr>
                    <?php 
    }
    ?>
                    <tr valign="top">
                        <th scope="row"><?php 
    echo esc_html__( 'Dropbox App Key', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <?php 
    if ( !defined( 'AI_TTS_DROPBOX_APP_KEY' ) ) {
        ?>
                                <input type="text" name="ai_tts_settings[dropbox_app_key]" value="<?php 
        echo esc_attr( ai_tts_get_option( 'dropbox_app_key' ) );
        ?>"
                                <?php 
        if ( !empty( get_option( 'ai_tts_dropbox_refresh_token' ) ) ) {
            ?>disabled<?php 
        }
        ?> />
                            <?php 
    } else {
        ?>
                                <input type="text" value="<?php 
        echo esc_attr( AI_TTS_DROPBOX_APP_KEY );
        ?>" title="<?php 
        echo esc_html__( 'This option is set in wp-config.php', 'ai-text-to-speech' );
        ?>" disabled />
                            <?php 
    }
    ?>
                        </td>
                    </tr>
                    <tr valign="top">
                        <th scope="row"><?php 
    echo esc_html__( 'Dropbox App Secret', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <?php 
    if ( !defined( 'AI_TTS_DROPBOX_APP_SECRET' ) ) {
        ?>
                                <input type="<?php 
        if ( empty( get_option( 'ai_tts_dropbox_refresh_token' ) ) ) {
            ?>text<?php 
        } else {
            ?>password<?php 
        }
        ?>" name="ai_tts_settings[dropbox_app_secret]" value="<?php 
        echo esc_attr( ai_tts_get_option( 'dropbox_app_secret' ) );
        ?>"
                                <?php 
        if ( !empty( get_option( 'ai_tts_dropbox_refresh_token' ) ) ) {
            ?>disabled<?php 
        }
        ?> />
                            <?php 
    } else {
        ?>
                                <input type="password" value="" title="<?php 
        echo esc_html__( 'This option is set in wp-config.php', 'ai-text-to-speech' );
        ?>" disabled />
                            <?php 
    }
    ?>
                            <br/><br/>
                            <?php 
    if ( empty( get_option( 'ai_tts_dropbox_refresh_token' ) ) ) {
        ?>
                                <?php 
        if ( empty( ai_tts_get_option( 'dropbox_app_key' ) ) || empty( ai_tts_get_option( 'dropbox_app_secret' ) ) ) {
            ?>
                                <p><?php 
            echo esc_html__( 'Save changes first, then click the button below to connect to Dropbox.', 'ai-text-to-speech' );
            ?></p>
                                <br/>
                                <?php 
        }
        ?>
                                <a href="<?php 
        echo esc_url( admin_url( 'admin-post.php?action=start_dropbox_oauth_process' ) );
        ?>"
                                class="button button-primary"<?php 
        if ( empty( ai_tts_get_option( 'dropbox_app_key' ) ) || empty( ai_tts_get_option( 'dropbox_app_secret' ) ) ) {
            ?> style="pointer-events: none; opacity: 0.5;"<?php 
        }
        ?>>
                                    <?php 
        echo esc_html__( 'Connect to Dropbox', 'ai-text-to-speech' );
        ?>
                                </a>
                            <?php 
    } else {
        ?>
                            <!-- Connected to Dropbox -->
                            <p>
                                <span style="color: green; font-weight: bold;"><span class="dashicons dashicons-yes"></span> <?php 
        echo esc_html__( 'Connected to Dropbox', 'ai-text-to-speech' );
        ?></span>
                            </p>
                            <br/>
                            <!-- Show Access Token -->
                            <p style="font-size: 12px;">
                                <?php 
        if ( !ai_tts_get_option( 'dropbox_access_token' ) ) {
            refresh_dropbox_access_token();
        }
        ?>
                                <span><?php 
        echo esc_html__( 'Access Token:', 'ai-text-to-speech' );
        ?></span>
                                <?php 
        if ( get_option( 'ai_tts_dropbox_access_token' ) ) {
            ?>
                                    <span style="color: green;" class="dashicons dashicons-yes"></span>
                                <?php 
        } else {
            ?>
                                    <span style="color: red;" class="dashicons dashicons-no"></span>
                                <?php 
        }
        ?>
                            </p>
                            <!-- Show Refresh Token -->
                            <p style="font-size: 12px;">
                                <span><?php 
        echo esc_html__( 'Refresh Token:', 'ai-text-to-speech' );
        ?></span>
                                <?php 
        if ( get_option( 'ai_tts_dropbox_refresh_token' ) ) {
            ?>
                                    <span style="color: green;" class="dashicons dashicons-yes"></span>
                                <?php 
        } else {
            ?>
                                    <span style="color: red;" class="dashicons dashicons-no"></span>
                                <?php 
        }
        ?>
                            </p>
                            <br/>
                            <p>
                                <a href="<?php 
        echo esc_url( admin_url( 'admin-post.php?action=disconnect_dropbox' ) );
        ?>" class="button button-secondary">Disconnect</a>
                            </p>
                            <br/>
                            <p style="font-size: 12px;">
                                <?php 
        echo esc_html__( 'Ensure you have set the app permissions to have: files.content.write, files.content.read, files.metadata.write, files.metadata.read, sharing.write', 'ai-text-to-speech' );
        ?></p>
                            <p>
                            <p style="font-size: 12px;">
                                <?php 
        echo esc_html__( 'Note: If you update your app permissions or settings you will need to disconnect and reconnect the app.', 'ai-text-to-speech' );
        ?>
                            </p>
                            <?php 
    }
    ?>
                        </td>
                    </tr>
                </table>
                
                <script>
                jQuery(document).ready(function($) {
                    // Show/Hide based on file storage location
                    $('select[name="ai_tts_settings[file_storage_location]"]').change(function() {
                        if ($(this).val() == 'dropbox') {
                            $('.ai-tts-dropbox-credentials').show();
                            $('.ai-tts-local-credentials').hide();
                        } else {
                            $('.ai-tts-dropbox-credentials').hide();
                            $('.ai-tts-local-credentials').show();
                        }
                    });
                    $('select[name="ai_tts_settings[file_storage_location]"]').trigger('change');
                });
                </script>

                <hr style="margin: 21px 0 29px 0;" />

                <h2><?php 
    echo esc_html__( 'Player Label', 'ai-text-to-speech' );
    ?></h2>

                <!-- Customisations -->
                <table class="form-table">
                    <!-- Show player label -->
                    <tr valign="top">
                        <th scope="row"><?php 
    echo esc_html__( 'Show Player Label', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[show_player_label]" value="0">
                            <input type="checkbox" name="ai_tts_settings[show_player_label]" value="1" <?php 
    checked( ai_tts_get_option( 'show_player_label' ), true );
    ?> /> <?php 
    echo esc_html__( 'Show a text label under the audio player.', 'ai-text-to-speech' );
    ?>
                            <p class="description" style="font-size: 12px;"><?php 
    echo sprintf( wp_kses_post( __( 'Note: The <a href="%s" target="_blank">OpenAI usage policies</a> require you to provide a clear disclosure to end users that the TTS voice they are hearing is AI-generated and not a human voice.', 'ai-text-to-speech' ) ), 'https://openai.com/policies/usage-policies' );
    ?></p>
                        </td>
                    </tr>
                    <script>
                    jQuery(document).ready(function($) {
                        // Show player label if show_player_label is checked
                        $('input[name="ai_tts_settings[show_player_label]"]').change(function() {
                            if ($(this).is(':checked')) {
                                $('.ai-tts-player-label').show();
                            } else {
                                $('.ai-tts-player-label').hide();
                            }
                        });
                        $('input[name="ai_tts_settings[show_player_label]"]').trigger('change');
                    });
                    </script>
                    <!-- Player label -->
                    <tr valign="top" class="ai-tts-player-label" <?php 
    if ( ai_tts_get_option( 'show_player_label' ) != true ) {
        ?>style="display: none;"<?php 
    }
    ?>>
                        <th scope="row"><?php 
    echo esc_html__( 'Player Label', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <textarea name="ai_tts_settings[player_label]"
                            placeholder="<?php 
    echo esc_html__( 'Listen to the audio version of this article (generated by AI).', 'ai-text-to-speech' );
    ?>
                            "><?php 
    echo esc_attr( ai_tts_get_option( 'player_label' ) );
    ?></textarea>
                        </td>
                    </tr>
                </table>

                <hr style="margin: 21px 0 29px 0;" />

                <h2><?php 
    echo esc_html__( 'Post Types', 'ai-text-to-speech' );
    ?></h2>

                <!-- Post Types -->
                <table class="form-table">
                    <!-- Select Field either "All" or "Specific" -->
                    <tr valign="top">
                        <th scope="row"><?php 
    echo esc_html__( 'Enabled for Post Types', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <select name="ai_tts_settings[post_types]">
                                <option value="all" <?php 
    selected( ai_tts_get_option( 'post_types' ), 'all' );
    ?>><?php 
    echo esc_html__( 'All', 'ai-text-to-speech' );
    ?></option>
                                <option value="specific" <?php 
    selected( ai_tts_get_option( 'post_types' ), 'specific' );
    ?>><?php 
    echo esc_html__( 'Specific', 'ai-text-to-speech' );
    ?></option>
                            </select>
                            <p>
                                <?php 
    echo esc_html__( 'Select which post types you would like to enable the TTS feature for.', 'ai-text-to-speech' );
    ?>
                        </td>
                    </tr>
                    <!-- Post Types To Enable -->
                    <tr valign="top" class="ai-tts-post-types">
                        <th scope="row"><?php 
    echo esc_html__( 'Post Types To Enable', 'ai-text-to-speech' );
    ?></th>
                        <td>
                            <?php 
    global $post;
    $the_types = ai_tts_get_option( 'post_types_to_enable' );
    if ( !is_array( $the_types ) ) {
        $the_types = array();
    }
    $post_types = get_post_types( array(
        'public' => true,
    ) );
    foreach ( $post_types as $post_type ) {
        if ( !$post_type ) {
            continue;
        }
        ?>
                                <input type="checkbox" name="ai_tts_settings[post_types_to_enable][]"
                                value="<?php 
        echo esc_attr( $post_type );
        ?>" <?php 
        if ( in_array( $post_type, $the_types ) ) {
            echo 'checked';
        }
        ?> /> <?php 
        echo esc_html( $post_type );
        ?><br>
                                <?php 
    }
    ?>
                        </td>
                    </tr>
                    <script>
                    jQuery(document).ready(function($) {
                        // Show post types if specific is selected
                        $('select[name="ai_tts_settings[post_types]"]').change(function() {
                            if ($(this).val() == 'specific') {
                                $('.ai-tts-post-types').show();
                            } else {
                                $('.ai-tts-post-types').hide();
                            }
                        });
                        $('select[name="ai_tts_settings[post_types]"]').trigger('change');
                    });
                    </script>
                </table>

                <hr style="margin: 21px 0 29px 0;" />

                <h2><?php 
    echo esc_html__( 'Content Customisations', 'ai-text-to-speech' );
    ?></h2>

                <table class="form-table">
                    <!-- Include "Title" in the TTS -->
                    <tr valign="top">
                        <th scope="row">
                            <?php 
    echo esc_html__( 'Title', 'ai-text-to-speech' );
    ?>
                        </th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[include_title]" value="0" />
                            <input type="checkbox" name="ai_tts_settings[include_title]" value="1" <?php 
    checked( ai_tts_get_option( 'include_title' ), true );
    ?> />
                            <?php 
    echo esc_html__( 'Include the post title in the TTS audio.', 'ai-text-to-speech' );
    ?>
                        </td>
                    </tr>
                    <!-- Include "Author" in the TTS -->
                    <tr valign="top">
                        <th scope="row">
                            <?php 
    echo esc_html__( 'Author Name', 'ai-text-to-speech' );
    ?>
                        </th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[include_author]" value="0" />
                            <input type="checkbox" name="ai_tts_settings[include_author]" value="1" <?php 
    checked( ai_tts_get_option( 'include_author' ), true );
    ?> />
                            <?php 
    echo esc_html__( 'Include the "By *author name*" after the title, in the TTS for type "posts".', 'ai-text-to-speech' );
    ?>
                        </td>
                    </tr>
                    <!-- Include "Post Date" in the TTS -->
                    <tr valign="top">
                        <th scope="row">
                            <?php 
    echo esc_html__( 'Post Date', 'ai-text-to-speech' );
    ?>
                        </th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[include_date]" value="0" />
                            <input type="checkbox" name="ai_tts_settings[include_date]" value="1" <?php 
    checked( ai_tts_get_option( 'include_date' ), true );
    ?> />
                            <?php 
    echo esc_html__( 'Include the "Published on *date*" after the title, in the TTS for type "posts".', 'ai-text-to-speech' );
    ?>
                        </td>
                    </tr>
                    <!-- Include custom text before the content -->
                    <tr valign="top" <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>style="pointer-events: none; opacity: 0.5;"<?php 
    }
    ?>>
                        <th scope="row"><?php 
    echo esc_html__( 'Custom Text Before Content', 'ai-text-to-speech' );
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?> (PRO)<?php 
    }
    ?></th>
                        <td>
                            <textarea name="ai_tts_settings[custom_text_before_content]"><?php 
    echo esc_attr( ai_tts_get_option( 'custom_text_before_content' ) );
    ?></textarea>
                            <p><?php 
    echo esc_html__( 'Add custom text before the content in the TTS audio.', 'ai-text-to-speech' );
    ?></p>
                        </td>
                    </tr>
                    <!-- Include custom text after the content -->
                    <tr valign="top" <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>style="pointer-events: none; opacity: 0.5;"<?php 
    }
    ?>>
                        <th scope="row"><?php 
    echo esc_html__( 'Custom Text After Content', 'ai-text-to-speech' );
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?> (PRO)<?php 
    }
    ?></th>
                        <td>
                            <textarea name="ai_tts_settings[custom_text_after_content]"><?php 
    echo esc_attr( ai_tts_get_option( 'custom_text_after_content' ) );
    ?></textarea>
                            <p><?php 
    echo esc_html__( 'Add custom text after the content in the TTS audio.', 'ai-text-to-speech' );
    ?></p>
                        </td>
                    </tr>
                </table>

                <hr style="margin: 21px 0 29px 0;" />

                <div <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>style="pointer-events: none; opacity: 0.5;"<?php 
    }
    ?>>

                    <h2><?php 
    echo esc_html__( 'Player Customisations', 'ai-text-to-speech' );
    ?>
                    <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>
                        <span style="font-size: 15px; font-weight: bold; color: #333;">(PRO)</span>
                    <?php 
    }
    ?>
                    </h2>
                    <!-- Custom Styles -->
                    <table class="form-table">
                        <!-- Player Background Color -->
                        <tr valign="top">
                            <th scope="row"><?php 
    echo esc_html__( 'Player Background Color', 'ai-text-to-speech' );
    ?></th>
                            <td>
                                <input type="color" name="ai_tts_settings[player_background_color]" value="<?php 
    echo esc_attr( ai_tts_get_option( 'player_background_color' ) );
    ?>" class="ai-tts-color-field" />
                                <p><?php 
    echo esc_html__( 'Set the background color of the audio player.', 'ai-text-to-speech' );
    ?></p>
                                <p><?php 
    echo esc_html__( 'Note: The text color will automatically adjust based on the background color.', 'ai-text-to-speech' );
    ?></p>
                            </td>
                        </tr>
                        <!-- Player Height: Normal, Compact, Large -->
                        <tr valign="top">
                            <th scope="row"><?php 
    echo esc_html__( 'Player Height', 'ai-text-to-speech' );
    ?></th>
                            <td>
                                <select name="ai_tts_settings[player_height]">
                                    <option value="default" <?php 
    selected( ai_tts_get_option( 'player_height' ), 'default' );
    ?>><?php 
    echo esc_html__( 'Large (Default)', 'ai-text-to-speech' );
    ?></option>
                                    <option value="medium" <?php 
    selected( ai_tts_get_option( 'player_height' ), 'medium' );
    ?>><?php 
    echo esc_html__( 'Medium', 'ai-text-to-speech' );
    ?></option>
                                    <option value="compact" <?php 
    selected( ai_tts_get_option( 'player_height' ), 'compact' );
    ?>><?php 
    echo esc_html__( 'Small (Compact)', 'ai-text-to-speech' );
    ?></option>
                                </select>
                                <p><?php 
    echo esc_html__( 'Set the height of the audio player.', 'ai-text-to-speech' );
    ?></p>
                            </td>
                        </tr>
                        <!-- Player Speed -->
                        <tr valign="top">
                            <th scope="row"><?php 
    echo esc_html__( 'Default Player Speed', 'ai-text-to-speech' );
    ?></th>
                            <td>
                                <input type="number" name="ai_tts_settings[player_speed]" value="<?php 
    echo esc_attr( ai_tts_get_option( 'player_speed' ) );
    ?>" step="0.1" min="0.5" max="2" />
                                <p><?php 
    echo esc_html__( 'Set the default speed of the audio player.', 'ai-text-to-speech' );
    ?></p>
                            </td>
                        </tr>
                    </table>

                    <hr style="margin: 21px 0 29px 0;" />

                    <div <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>style="pointer-events: none; opacity: 0.5;"<?php 
    }
    ?>>

                        <h2><?php 
    echo esc_html__( 'Statistics and Analytics', 'ai-text-to-speech' );
    ?>
                        <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>
                            <span style="font-size: 15px; font-weight: bold; color: #333;">(PRO)</span>
                        <?php 
    }
    ?>
                        </h2>
                        <table class="form-table">
                            <!-- Enable Statistics -->
                            <tr valign="top">
                                <th scope="row"><?php 
    echo esc_html__( 'Enable TTS Statistics', 'ai-text-to-speech' );
    ?></th>
                                <td>
                                    <input type="hidden" name="ai_tts_settings[enable_statistics]" value="0">
                                    <input type="checkbox" name="ai_tts_settings[enable_statistics]" value="1" <?php 
    if ( aitts_fs()->is_paying_or_trial() ) {
        checked( ai_tts_get_option( 'enable_statistics' ), true );
    }
    ?> />
                                    <?php 
    echo esc_html__( 'Enable TTS usage statistics and analytics features.', 'ai-text-to-speech' );
    ?>
                                </td>
                            </tr>
                        </table>

                    </div>

                </div>                             

            <br/>

            <?php 
    submit_button();
    ?>

        </form>

    </div>

	<div class="ai-tts-settings-sidebar">

            <div class="ai-tts-settings-sidebar-box">

                <p>
                <a href="https://relywp.com/plugins/ai-text-to-speech/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar" target="_blank" style="font-size: 15px; font-weight: bold;">AI Text to Speech<?php 
    if ( aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?> (PRO)<?php 
    }
    ?></a>

                <span style="font-size: 10px;"><?php 
    echo esc_html__( 'Developed by', 'ai-text-to-speech' );
    ?>
                    <a href="https://relywp.com/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar" target="_blank"
                    title="www.relywp.com">RelyWP</a>
                </span>
                </p>

            </div>

            <br />

            <?php 
    if ( !aitts_fs()->is_paying_or_trial() ) {
        // Premium only
        ?>
            <div class="ai-tts-settings-sidebar-box">
                <h3 style="font-weight: bold;"><?php 
        echo esc_html__( 'Want more features? Upgrade to PRO!', 'ai-text-to-speech' );
        ?></h3>
                <p style="font-size: 15px;">
                    - <?php 
        echo esc_html__( 'TTS audio player usage statistics', 'ai-text-to-speech' );
        ?>
                    <br/>- <?php 
        echo esc_html__( 'Audio player style customisations', 'ai-text-to-speech' );
        ?>
                    <br />- <?php 
        echo esc_html__( 'Dropbox file storage location', 'ai-text-to-speech' );
        ?>
                    <br />- <?php 
        echo esc_html__( 'Global custom text before/after content', 'ai-text-to-speech' );
        ?>
                    <br />- <?php 
        echo esc_html__( 'Customise TTS content for each post', 'ai-text-to-speech' );
        ?>
                    <br />- <?php 
        echo esc_html__( 'And more features coming soon..', 'ai-text-to-speech' );
        ?>
                    <br/>
                    <a href="https://relywp.com/plugins/ai-text-to-speech/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar"
                    target="_blank" style="font-size: 15px;"><?php 
        echo esc_html__( 'Learn more about PRO', 'ai-text-to-speech' );
        ?></a>
                </p>
				<p style="font-size: 17px; font-weight: bold; color: #333;">
					<?php 
        echo esc_html__( 'Access all features for only', 'ai-text-to-speech' );
        ?> $29!
				</p>
                <p><a href="<?php 
        echo aitts_fs()->get_upgrade_url();
        ?>" target="_blank"
                    style="font-size: 17px; font-weight: bold;"
                        class="button button-primary"><?php 
        echo esc_html__( 'Upgrade to PRO', 'ai-text-to-speech' );
        ?> <span class="dashicons dashicons-arrow-right-alt"
                        style="margin-top: 10px; font-size: 19px;"></span></a></p>
                <p style="font-size: 12px; font-weight: bold; color: red;">Limited time! 10% discount with code: LAUNCH10</p>
            </div>

            <br />

            <?php 
    }
    ?>

            <?php 
    global $aitts_fs;
    ?>
            <div class="ai-tts-settings-sidebar-box">
                <h3 style="font-weight: bold;"><?php 
    echo esc_html__( 'Support', 'ai-text-to-speech' );
    ?></h3>
                <p style="font-size: 15px;"><a href="https://relywp.com/plugins/ai-text-to-speech/docs?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar" target="_blank"><?php 
    echo esc_html__( 'View Plugin Documentation', 'ai-text-to-speech' );
    ?></a></p>
                <p style="font-size: 15px;"><?php 
    echo esc_html__( 'Need help? Have a suggestion?', 'ai-text-to-speech' );
    ?>
                <?php 
    ?>
                    <a href="https://wordpress.org/support/plugin/ai-text-to-speech/" target="_blank">
                <?php 
    ?>
                    <?php 
    echo esc_html__( 'Get Support', 'ai-text-to-speech' );
    ?>
                </a></p>
                <?php 
    ?>
            </div>

            <br />

            <div class="ai-tts-settings-sidebar-box">

                <p style="font-size: 12px; font-weight: bold;"><?php 
    echo esc_html__( 'Check out some of our other plugins:', 'ai-text-to-speech' );
    ?>
                    <br/>
                    - <a href="https://couponaffiliates.com/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar" target="_blank" title="">Coupon Affiliates for WooCommerce</a>
                    <br/>
                    - <a href="https://relywp.com/plugins/tax-exemption-woocommerce/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar" target="_blank" title="">Tax Exemption for WooCommerce</a>
                    <br/>
                    - <a href="https://relywp.com/plugins/advanced-customer-reports-woocommerce/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=sidebar" target="_blank" title="">Advanced Customer Reports for WooCommerce</a>
                    <br/>
                    - <a href="https://wordpress.org/plugins/simple-cloudflare-turnstile/" target="_blank" title="">Simple Cloudflare Turnstile</a> (FREE)
                    <br/>
                    - <a href="https://wordpress.org/plugins/recaptcha-woo/" target="_blank" title="">reCAPTCHA for WooCommerce</a> (FREE)
                    <br/>
                </p>

            </div>

        </div>

    <?php 
}

add_action( 'admin_init', 'ai_tts_admin_init' );
function ai_tts_admin_init() {
    register_setting( 'ai_tts_settings', 'ai_tts_api_key' );
    register_setting( 'ai_tts_settings', 'ai_tts_settings' );
}

function ai_tts_add_to_error_log(  $message  ) {
    $ai_tts_error_log = ai_tts_get_option( 'error_log' );
    $ai_tts_error_log = "/n" . date( 'Y-m-d H:i:s' ) . ' - ' . $message . $ai_tts_error_log;
    $ai_tts_error_log = explode( "/n", $ai_tts_error_log );
    if ( count( $ai_tts_error_log ) > 10 ) {
        array_shift( $ai_tts_error_log );
    }
    $ai_tts_error_log = implode( "/n", $ai_tts_error_log );
    $options = get_option( 'ai_tts_settings' );
    if ( !$options ) {
        $options = array();
    }
    $options['error_log'] = $ai_tts_error_log;
    update_option( 'ai_tts_settings', $options );
}
